name: Flutter CI

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🎨 Format
        run: dart format --output=none --set-exit-if-changed .

      - name: 📝 Create dummy .env
        run: touch .env

      - name: 🔍 Analyze
        run: flutter analyze

      - name: 🧪 Run tests
        run: flutter test

      - name: 📊 SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: frontend
          args: >
            -Dsonar.projectKey=ADNAN-ZEYA_SafeChat-2.0
            -Dsonar.organization=adnan-zeya
            -Dsonar.sources=lib
